### ISSUE TITLE
ICT time zone code displays as +07

### ISSUE THREAD

**Issue by Kalsta** [Zren/plasma-applet-eventcalendar#11]
Hi there,

I love this widget as in our company everyone works remotely, but one of our team just moved to Thailand and I discovered that the time zone displays as +07 instead of ICT (see attached screenshot).

Cheers,

Kal
![screen_20180326-184329](https://user-images.githubusercontent.com/4401117/37893336-61da1018-3126-11e8-8276-598360074fb0.png)

**Comment by Zren** [comment]
This bug is in digitalclock too.

* https://github.com/KDE/plasma-workspace/blob/master/applets/digital-clock/package/contents/ui/Tooltip.qml#L62
* https://github.com/KDE/plasma-workspace/blob/master/dataengines/time/timesource.cpp#L102-L112
* http://doc.qt.io/qt-5/qtimezone.html#abbreviation
* https://github.com/qt/qtbase/blob/5.11/src/corelib/tools/qtimezone.cpp#L579
* https://github.com/qt/qtbase/blob/5.11/src/corelib/tools/qtimezoneprivate_tz.cpp
* https://github.com/qt/qtbase/blob/5.11/src/corelib/tools/qtimezoneprivate_data_p.h#L263
* Not sure where to go from there.

Looks like it might be a Qt ...bug?

Or maybe it's `+07` instead of `ICT` in thailands local language, and it's the english translation that's "wrong"?

I could make a quick override if you want though.

```
If (displayTimezoneAsCode && dataSource.data[zone]["Timezone Abbreviation"] == "+07") {
    return "ICT"
}
```

Though this override might be considered a "bug" to those from Thailand.

**Comment by Kalsta** [comment]
Thank you for the prompt response!

I can ask my coworker what the locals refer to their timezone as and get back to you if you like?

Cheers,

Kal

**Comment by Kalsta** [comment]
Sorry for the delayed response, I finally got around to speaking with my coworker and he said they actually use both so it appears not to be something that would need changing at this stage, but I appreciate you getting back to me with you suggestions. I'll close this now. Cheers, Kal.
