### ISSUE TITLE
minor gui issues

### ISSUE THREAD

**Issue by alekksander** [Zren/plasma-applet-eventcalendar#118]
1. scrollbar overlaps content:
![Screenshot_20200119_233929](https://user-images.githubusercontent.com/3148302/72689745-0146f180-3b15-11ea-8279-c2b73b4a09fe.png)

2. check–marks are inconsistent
![Screenshot_20200119_234137](https://user-images.githubusercontent.com/3148302/72689770-5256e580-3b15-11ea-9f7f-8e1e4a8540f3.png)

**Comment by Zren** [comment]
> scrollbar overlaps content

That applies to all "widget config" tabs. You can see the effect in Task Manager. I'm probably the only one who uses GroupBoxes to outline sections however. Other "widgets" embed their own ScrollView, as you see whenever there's a table. I could add padding on the right side I guess though...

![2020-01-19___18-24-44](https://user-images.githubusercontent.com/416367/72690292-f9715800-3ae8-11ea-85ea-fbf6d8c318b3.png)

> check–marks are inconsistent

In order to make a checkbox without any space wasted on a empty label (for the sound effect on/off toggle), I have to override the CheckBoxStyle. I'm probably using the wrong "CheckBoxStyle" as a base.

Same reasoning for the checkmark checkboxes in the google calendar list, as I override the label with a calendar color rectangle and a "locked" icon.

**Comment by alekksander** [comment]
> in order to make a checkbox without any space wasted on a empty label 

sorry i should have clarify that. the issue in my understanding is not that empty space is there (this actually makes sense to me), but that styling is different than other check boxes.

**Comment by Zren** [comment]
For 1 (scrollbar overlap) it appears that it's been fixed in plasma-desktop master branch. 

https://phabricator.kde.org/D27608

So it'll be fixed in Plasma 5.19. I can probably use Kirigami sooner than that though, likely after Ubuntu 20.04 is shipped and everyone using 18.04 with Plasma 5.12 has upgraded.

**Comment by Zren** [comment]
For 2 (checkbox styling) it'll be fixed in v69 as I've decided to not use custom styling. I added the "SFX:" label to make the extra whitespace less noticeable.

![2020-06-29___13-25-18](https://user-images.githubusercontent.com/416367/86036502-fb323680-ba0b-11ea-9dba-9c84e755f8cb.png)
