### ISSUE TITLE
Apply button not activating on change

### ISSUE THREAD

**Issue by gdfox** [Zren/plasma-applet-eventcalendar#186]
Hi,

When I change an item the Apply button doesn't activate and when I click OK, nothing is getting saved.

Please advise...

Thanks,
Greg

**Comment by Zren** [comment]
The config controls will now auto-apply on change in this widget.

Which settings specifically is "not getting saved"?

**Comment by gdfox** [comment]
The only two I changed was the date format and the Google calendar sync. Neither saved.

**Comment by Zren** [comment]
Did you restart after updating? 

* v71 changed the names of the config keys.
* If you didn't restart plasmashell after updating, the widget in the panel will still be using the old config keys.
* However since the config window isn't always needed, it's loaded from the new disk when you open it (with the new files + config keys).

**Comment by gdfox** [comment]
Ah, I rebooted my computer and now all is well.

Thank you for providing a great widget.

Greg
