### ISSUE TITLE
Grid color ugly with dark themes

### ISSUE THREAD

**Issue by taprobane99** [Zren/plasma-applet-eventcalendar#201]
The near-black grid color on dark themes is too harsh and dominant. I changed it to Black Coral Pearl (hex `#54626f`), but perhaps there is a better option.

**Comment by Zren** [comment]
I use the `theme.buttonBackgroundColor` from the color theme by default.

https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/AppletConfig.qml#L24

The reason why it's configurable is because not every theme looks okay with it.

That said, it looks like Breeze Light/Dark no longer look good anymore as it's hard to read. Since the default looks bad I'll need to change it.

![2020-12-09___12-32-55](https://user-images.githubusercontent.com/416367/101665185-ad8a1300-3a1a-11eb-8101-7186d35d28b4.png)
![2020-12-09___12-34-38](https://user-images.githubusercontent.com/416367/101665419-f3df7200-3a1a-11eb-8654-c4d28d08e1bf.png)

Using `ColorUtil.lerp(theme.backgroundColor, theme.textColor, 0.9)` which is basically a 10% overlay of the `backgroundColor` onto the `textColor` it looks like:

![2020-12-09___12-44-32](https://user-images.githubusercontent.com/416367/101667196-06f34180-3a1d-11eb-9c54-774de1f3811b.png)
![2020-12-09___12-48-16](https://user-images.githubusercontent.com/416367/101667201-08246e80-3a1d-11eb-9737-5c70bfbe57ef.png)

**Comment by taprobane99** [comment]
44494d looks better on my system, although not sure its the best.

I'm using Spectrum Min. Classic plasma style which is dark and translucent, if that helps.

**Comment by Zren** [comment]
For that style, it'll use `#44494d` as the default generated color for the grid.

![2020-12-09___18-00-41](https://user-images.githubusercontent.com/416367/101699014-77638800-3a48-11eb-8fc0-c0af8427aa91.png)

**Comment by taprobane99** [comment]
Ok. It still looks a little "heavy" and dominant, but I guess that's personal taste.
