### ISSUE TITLE
Scrolling with the touchpad is too fast

### ISSUE THREAD

**Issue by RaitaroH** [Zren/plasma-applet-eventcalendar#4]
Open the even calendar, hover the agenda then try to scroll. If I do it with the mouse is nice, but with the touchpad I scroll by weeks instead of days.

Also this was filled because I have a similar bug here: https://bugs.kde.org/show_bug.cgi?id=388353
I also have the issue with pager and vlc. But I was suggested to file individual bugs.

**Comment by Zren** [comment]
Which version of event calendar btw? Open the config, it'll say it in the top right.

**Comment by RaitaroH** [comment]
Version 51. I am also on KDE Neon 5.12.3

Also as I mentioned I have this issue with many things not just this.

**Comment by Zren** [comment]
Ah so it affects other things in the panel like the application launcher, network list, etc?

**Comment by RaitaroH** [comment]
The taskmanager yes, the network list no.

**Comment by Zren** [comment]
Try v53, I changed the way I "list" the agenda, affecting how things scroll. Before it would only draw the visible "days" with their events, but this caused it to stutter when scrolling sometimes. Now it draws everything when the month changes.

Anyways, try v53. Go to get new widgets > update > v53.

Then restart plasmashell with `killall plasmashell; kstart5 plasmashell`

**Comment by RaitaroH** [comment]
In the store there was just update. I had to remove the original on the panel, install v53, readd the calendar and reconfigure it, but now it works.

So what exactly was the problem though? I am curious because I get this issue a lot.

**Comment by Zren** [comment]
> I had to remove the original on the panel, install v53,

You didn't have to remove it, just restart plasmashell after updating. Oh well you got it working.

> So what exactly was the problem though? I am curious because I get this issue a lot.

I was using Qt's ListView inside a ScrollView. Qt probably had a bug when handling the touch scrolling. A mouse wheel "click" will scroll +120 units. However you want a touchpad to be more responsive right? So it'll fire an event every ~30 units or so. So you end up having 4-6 events fired with the touchpad for every mouse click.

I changed this to use a Repeater instead of a ListView. The Repeater will draw all 30 days of the month in the background. A ListView might only show the 5 days that are currently visible, and draw the rest when you scroll them into view.

Qt's ListView is used in lots of plasma's widgets since it's suppose to be more memory efficient for very large lists. My code is pretty slow however, so drawing a new "list item" will cause a stutter when scrolling which is why I no longer use it.
