### ISSUE TITLE
it's raining holidays (dupes) / personal entry doesn't save

### ISSUE THREAD

**Issue by alekksander** [Zren/plasma-applet-eventcalendar#7]
→this is fresh install before any configuration. as seen on attached picture holiday displays twice. if reload button is pushed (one at the bottom, there is no balloon tip over it, so i don't know it's name) all holidays multiply itself (so few  presses results in absolutely bloated ) these entries cannot be deleted – entry to delete is greyed out.
![screenshot_20180318_071614](https://user-images.githubusercontent.com/3148302/37563238-819dba86-2a7c-11e8-9170-3a669fb8ba64.png)

→ personal note cannot be added to any chosen day – i input text, press „enter” and it all disappears.

ps. this is polish localization. i believe this is not the same as  #14
Thank You

**Comment by Zren** [comment]
"Wielkanoc" appears to have duped, but not "Wielki Piatek"? Weird.

Which Holidays region are you using, as Poland doesn't show Wielki.

![](https://i.imgur.com/daLQm2G.png)

**Comment by Zren** [comment]
Er, nevermind, in my timezone, Wielkanoc is on April 2nd. I also have it showing up twice in pl_pl.

Under digitalclock, it seems the event lasts 2 days for me (Apr 1 + Apr 2). So it appears that when the events are fetched, I'm placing it on the wrong "date".

**Comment by Zren** [comment]
Or not. I guess KHolidays creates 2 events "items" in their data for multi day events. If I go into eventcalendar's settings and change "Show multi-day events" from "only on the first day" to "on all days" I get:

![](https://i.imgur.com/fZ5lbdr.png)

KHolidays defines it as:

* https://github.com/KDE/kholidays/blob/master/holidays/plan2/holiday_pl_pl#L21
* `"Wielkanoc"              public religious on easter length 2 days`

To confirm this, we can check "Boże Narodzenie" on december 25th.

* `"Boże Narodzenie"        public religious on december 25 length 2 days`

Hmmm... Looks like I forgot to test if other months besides the current month can show events from KHolidays, as it seems that you can only see those from +-30 days from the current date. Found a bug!

Anyways, after fixing that bug:

![](https://i.imgur.com/Nhjk2ln.png)

So it seems I need to filter out the repeated "event items" caused by multi-day events in KHoliday.

**Comment by alekksander** [comment]
http://www.youtube.com/watch?v=E-WHW-QNswE
