### ISSUE TITLE
Google Calendar uses a lot of CPU

### ISSUE THREAD

**Issue by afettouhi** [Zren/plasma-applet-eventcalendar#85]
I am running Arch Linux with KDE Plasma 5.16 and I am using the event calendar widget installed via plasma-widgets. I noticed yesterday that widget for some reason eats up almost 50 % of CPU and the calendar part of the widget jumps up and down between various entries. I then disconnected from the google calendar plugin and everything was back to normal. Tried to connect it again but it the same thing happened again.

**Comment by Zren** [comment]
Oooooh no. This was bad coding. I assumed an all errors == the access token had expired. So it would then attempt to renew the token and fetch the events again right away. There's no throttling or counting the number of errors before giving up or waiting a few seconds longer each attempt. Google Calendar rarely has service outages so I never considered it going down...

Google Calendar went through down time yesterday. Every event calendar install then started fetching 3-4 requests every second in a loop.

We burned through the entire daily quota, and users are probably hitting the 500 requests per 100 seconds as well.

![2019-06-19___02-11-19](https://user-images.githubusercontent.com/416367/59741217-572e8080-9238-11e9-9bbd-5572ac7744a6.png)

```
qml: [eventcalendar:debug] fetchGCalEventsPage.response abcdef@group.calendar.google.com HTTP Error 403: Forbidden {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceeded",
    "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/calendar-json.googleapis.com/quotas?project=391436299960",
    "extendedHelp": "https://console.developers.google.com/apis/api/calendar-json.googleapis.com/quotas?project=391436299960"
   }
  ],
  "code": 403,
  "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/calendar-json.googleapis.com/quotas?project=12345678"
 }
}
```

It should be automatically fixed in a few hours when we hit midnight PST as google calendar is back up. I will definitely properly handle errors in the next version.

**Comment by afettouhi** [comment]
OK I will try to use it again in a few hours. Thanks for the swift reply.

**Comment by Zren** [comment]
It appears we also hit the OpenWeatherMap quota as well yesterday.

> Dear Customer,  
> Your OpenWeatherMap API key is temporary blocked due to the continual sufficient exceeding of the calls per minute limit by performing **662 requests** within a minute but the limit for the Free account is **60 rpm**.

I assume that was from people performing a manual refresh when the event list wasn't loading (which have refreshed the weather as well). The weather handled errors by not updating the meteogram. I expected to hit the 60rpm limit before, so I planned for it to just reuse the existing data if there was an error. The meteogram uses a the hourly dataset which has 4 day forecast of data.

------

Here's a few screenshots of the Google Calender API metrics for posterity.

I'm a little worried that the quota is already half way used up for today. I'll need to keep monitoring and check back tomorrow.

![2019-06-19___12-21-42](https://user-images.githubusercontent.com/416367/59783081-58d66380-928d-11e9-82f3-2f7cef0a8ecf.png)
![2019-06-19___12-23-33](https://user-images.githubusercontent.com/416367/59783096-612e9e80-928d-11e9-9bdb-bc7438a8bb77.png)
![2019-06-19___12-25-15](https://user-images.githubusercontent.com/416367/59783101-62f86200-928d-11e9-82fe-788233489bf6.png)

**Comment by Zren** [comment]
This should no longer happen in v64.
