### ISSUE TITLE
When set as single column the widget looks really thin

### ISSUE THREAD

**Issue by ekaradon** [Zren/plasma-applet-eventcalendar#89]
Hello,

Recently, I got a weird size for this widget when set as mono column, see below:

![Screenshot_20190705_153656](https://user-images.githubusercontent.com/9439390/60725992-baa7f600-9f3a-11e9-85d4-97e853d1ece6.png)

I would like to have a larger column or to be able to resize it. Is it possible?

Anyway, thanks for this awesome plugin!

**Comment by Zren** [comment]
Edit `Layout.preferredWidth` in `PopupView.qml`.

* `~/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml`
* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/PopupView.qml#L33

To restart the `plasmashell` process, run `killall plasmashell; kstart5 plasmashell` or relog.

I might make it optional in the future, but that should work for now.

**Comment by ekaradon** [comment]
Okay, thanks ! I don't know why but this morning the widget has the right size without me doing anything. Maybe related to screen display.

**Comment by Zren** [comment]
Hmm. I wonder if the "preferredWidth" property binding broke somehow, and it then defaulted to the "minimumWidth". Well anyways, if it happens again, notify me (so I know how common the issue is), then use `Alt+RightClick+Drag` to resize the popup window. The new size will be forgotten when plasma restarts but should fix the issue in the immediate session.
